version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: content_agent_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: content_agent_postgres
    ports:
      - "5433:5432"  # Non-standard port as requested
    environment:
      - POSTGRES_DB=content_agent
      - POSTGRES_USER=agent_user
      - POSTGRES_PASSWORD=agent_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  qdrant_storage:
  postgres_data: